// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsDotnet.Models;

namespace WinFormsDotnet.Migrations
{
    [DbContext(typeof(CUSERSBUS209DOCUMENTSHTDOCSWINFORM47WINFORMSDOTNETBINDEBUGNETCOREAPP31MYDBMDFContext))]
    partial class CUSERSBUS209DOCUMENTSHTDOCSWINFORM47WINFORMSDOTNETBINDEBUGNETCOREAPP31MYDBMDFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");
#pragma warning restore 612, 618
        }
    }
}
