'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebLogAnalyzer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animacion1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animacion1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Web Log Analyzer.
        '''</summary>
        Friend ReadOnly Property AppName() As String
            Get
                Return ResourceManager.GetString("AppName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Internal Server Error (500).
        '''</summary>
        Friend ReadOnly Property HttpCodeInternalServerError() As String
            Get
                Return ResourceManager.GetString("HttpCodeInternalServerError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Not Found (404).
        '''</summary>
        Friend ReadOnly Property HttpCodeNotFound() As String
            Get
                Return ResourceManager.GetString("HttpCodeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Not Modified (304).
        '''</summary>
        Friend ReadOnly Property HttpCodeNotModified() As String
            Get
                Return ResourceManager.GetString("HttpCodeNotModified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Other.
        '''</summary>
        Friend ReadOnly Property HttpCodeOther() As String
            Get
                Return ResourceManager.GetString("HttpCodeOther", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Succeeded (200).
        '''</summary>
        Friend ReadOnly Property HttpCodeSucceeded() As String
            Get
                Return ResourceManager.GetString("HttpCodeSucceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Unauthorized (401).
        '''</summary>
        Friend ReadOnly Property HttpCodeUnauthorized() As String
            Get
                Return ResourceManager.GetString("HttpCodeUnauthorized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Invalid date directive..
        '''</summary>
        Friend ReadOnly Property InvalidDateDirective() As String
            Get
                Return ResourceManager.GetString("InvalidDateDirective", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Invalid date or time found in {0}..
        '''</summary>
        Friend ReadOnly Property InvalidDateOrTime() As String
            Get
                Return ResourceManager.GetString("InvalidDateOrTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Invalid fields directive in {0}..
        '''</summary>
        Friend ReadOnly Property InvalidFieldsDirective() As String
            Get
                Return ResourceManager.GetString("InvalidFieldsDirective", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Invalid log entry found in {0}..
        '''</summary>
        Friend ReadOnly Property InvalidLogEntry() As String
            Get
                Return ResourceManager.GetString("InvalidLogEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Invalid log file: {0}..
        '''</summary>
        Friend ReadOnly Property InvalidLogFile() As String
            Get
                Return ResourceManager.GetString("InvalidLogFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Invalid status value in {0}..
        '''</summary>
        Friend ReadOnly Property InvalidStatusValue() As String
            Get
                Return ResourceManager.GetString("InvalidStatusValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to determine access time in {0}..
        '''</summary>
        Friend ReadOnly Property MissingAccessTime() As String
            Get
                Return ResourceManager.GetString("MissingAccessTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Log file does not contain cs-uri-stem field..
        '''</summary>
        Friend ReadOnly Property MissingUriStem() As String
            Get
                Return ResourceManager.GetString("MissingUriStem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No log files found in {0}..
        '''</summary>
        Friend ReadOnly Property NoLogFiles() As String
            Get
                Return ResourceManager.GetString("NoLogFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Web Log Analysis.
        '''</summary>
        Friend ReadOnly Property ReportDisplayName() As String
            Get
                Return ResourceManager.GetString("ReportDisplayName", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
